name: 自动更新 JSON 数据

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装 pnpm
        run: npm install -g pnpm

      - name: 安装依赖
        run: pnpm install

      - name: 运行更新脚本
        run: |
          npx tsx scripts/updateBvJson.ts ys
          npx tsx scripts/updateBvJson.ts bt
          npx tsx scripts/updateBvJson.ts zzz

      - name: 提交并推送更新的 JSON 文件
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/json/
          git diff --cached --quiet || git commit -m "chore: 更新 JSON 数据 [skip ci]"
          git push
